name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - run: scripts/ci.sh

      - uses: ./.github/actions/analyze
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          qlty-coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}

      - run: scripts/goreleaser.sh release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}

      - uses: siakhooi/publish-to-repo-action@9be1278553e6c9c0a48a3b5c5da567e30f1bf895 # v1.0.0
        with:
          token: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
          config-file: publish-to-apt.yml

      - uses: siakhooi/publish-to-repo-action@9be1278553e6c9c0a48a3b5c5da567e30f1bf895 # v1.0.0
        with:
          token: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
          config-file: publish-to-rpms.yml
